### PR TITLE
♥ Fixed the heart emoji in cutefetch

### PR DESCRIPTION
**Pull request by Kalitsune**
image
The heart in the window manager section presented a display issue. This Pull Request changes the glyph for the window manager to a heart glyph from the widely used [NerdFont](https://www.nerdfonts.com/).

This pull request is a follow up from the discussion in #7.

### CODE REVIEW

**Comment by Kalitsune** [comment]
BTW while editing the README.md I've noticed the # Extra instruction to randomize the animals face and I find it funny because I did something kinda similar but with a predefined set of faces (because some of them are too big to fit on this cat)

This is my fetch function:
```sh
# welcome screen
fetch () {
  eyes=(0 1 2 3 4 6 7 8 11 12 14)
  cutefetch -k2 $(shuf -e "${eyes[@]}" -n 1)
}
fetch
```

**Comment by cybardev** [comment]
Huh, wow. Didn't realize the shuf command could be shortened like that just by using an array. Thanks for the info and suggestions.

I'll play around with it a bit and see if I want to implement something like that internally.
Will keep as is for now, but I'll let you know.

**Comment by cybardev** [comment]
An interesting thing I notice with the dev branch is that the heart changed on my Mac.

image

So, previously on Mac I had outline heart, and on Linux it was broken. Now, on Linux I have an outline heart and on Mac it's filled.

I do use NerdFonts everywhere (and have been for years), so not sure what's happening. Maybe my Mac has outdated NerdFonts or something. Will have to look into it.

Regardless, it looks good on both platforms, so I'll merge it now.
Thanks again for your wonderful contributions. 😊

**Review by cybardev — APPROVED** [review]
Looks good to me. Merging.

**Comment by Kalitsune** [comment]
yay that'd be wonderful!

> Huh, wow. Didn't realize the shuf command could be shortened like that just by using an array. Thanks for the info and suggestions.
> 
> I'll play around with it a bit and see if I want to implement something like that internally. Will keep as is for now, but I'll let you know.

**Comment by Kalitsune** [comment]
Thank you for making this awesome project. Btw you should submit a pull request to add it to https://github.com/fosslife/awesome-ricing#fetches

**Comment by cybardev** [comment]
Thanks a lot for the suggestion. I'll definitely make a PR to add it there. Didn't even know it existed 😅

**Comment by cybardev** [comment]
@Kalitsune Made a new issue (#9) for the randomizer. Let me know if you'd like to implement it, since you already have most of the code ready. No worries if you're too busy; I can do it later too if need be.

**Comment by Kalitsune** [comment]
Hi, I will try to implement it if I have the time!
Not really sure if I'll have the time today tho

**Comment by cybardev** [comment]
> Hi, I will try to implement it if I have the time!
> Not really sure if I'll have the time today tho

Sure. Feel free to whenever. It's just a fetch script that very few people use anyway, so nothing urgent. Thanks a lot.

**Pull request merged**
